### PR TITLE
Add payment command

### PR DESCRIPTION
**Pull request by ChillarAnand**

### CODE REVIEW

**Comment by subho007** [comment]
@dhilipsiva do we need payment functionality in CLI ? or do we just make it ?

**Comment by dhilipsiva** [comment]
I don't think that users will use CLI to make payments. Like ever. But, there is no Harm in having it. But none of the tools/libraries that I know of make paments through CLI / libraries. 😛

**Comment by dhilipsiva** [comment]
@rultor hello

**Comment by ChillarAnand** [comment]
I don't think any one will make payment wit CLI. It just makes testing payment bit easier.

**Comment by dhilipsiva** [comment]
Upvote

On Mon, Jul 11, 2016 at 10:42 AM Anand Pandikunta <notifications@github.com>
wrote:

> I don't think any one will make payment wit CLI. It just makes testing
> payment bit easier.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/appknox/appknox-python/pull/12#issuecomment-231643641>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAepmmBZ18aPqRhpdFxnyMGrNlpa_G05ks5qUdDQgaJpZM4JEM43>
> .
>
-- 

--

dhilipsiva

Full Stack & DevOps Engineer.


Website : http://dhilipsiva.com

Github  : https://github.com/dhilipsiva

Twitter : https://twitter.com/dhilipsiva

Email   : dhilipsiva@gmail.com

Mobile  : +91 81977 93582

**Pull request merged**
